- hosts: remoto
  gather_facts: False

  tasks:
   - name: Listando arquivos
     block:
      - name: Exibindo um mensagem
        debug:
          msg: "Executando normalmente"

      - name: Forcando um erro
        command: /bin/false

      - name: Task ser√° executada
        debug:
          msg: "Essa mensagem sera exibida"

     rescue: 
       - name: Exibindo os erros
         debug:
           msg: "Um erro foi encontrado e precisa ser corrigido"